#!/bin/bash
# ===========================================
# Kinder CRM - Production Server Setup Script
# Server: 213.109.146.167
# Domain: schoolkids.kz
# ===========================================

set -e

echo "======================================"
echo "  KINDER CRM - PRODUCTION SERVER SETUP"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Step 1: Update System
echo -e "${YELLOW}[1/7] Updating system packages...${NC}"
sudo apt update
sudo DEBIAN_FRONTEND=noninteractive apt upgrade -y
echo -e "${GREEN}✓ System updated${NC}"

# Step 2: Install essential packages
echo -e "${YELLOW}[2/7] Installing essential packages...${NC}"
sudo apt install -y \
  curl wget git vim htop unzip \
  build-essential ca-certificates \
  gnupg lsb-release ufw fail2ban \
  pwgen openssl
echo -e "${GREEN}✓ Essential packages installed${NC}"

# Step 3: Configure SSH Hardening
echo -e "${YELLOW}[3/7] Hardening SSH configuration...${NC}"
sudo cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d)

sudo tee /etc/ssh/sshd_config > /dev/null <<'SSHEOF'
# Kinder CRM - Hardened SSH Configuration
# Generated by server-setup.sh

# Network Configuration
Port 22
AddressFamily inet
ListenAddress 0.0.0.0

# Authentication
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
PermitEmptyPasswords no
ChallengeResponseAuthentication no
UsePAM yes

# Key-based auth only
AuthorizedKeysFile .ssh/authorized_keys

# Security Settings
Protocol 2
StrictModes yes
MaxAuthTries 3
MaxSessions 10
LoginGraceTime 30s
ClientAliveInterval 300
ClientAliveCountMax 2

# Disable dangerous features
X11Forwarding no
AllowTcpForwarding no
PermitTunnel no
GatewayPorts no

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Override for specific users
Match User yaro
    PasswordAuthentication no
    PubkeyAuthentication yes
SSHEOF

# Verify SSH config before restarting
sudo sshd -t
if [ $? -eq 0 ]; then
    echo -e "${GREEN}✓ SSH configuration valid${NC}"
    echo -e "${YELLOW}WARNING: SSH will now be restarted. Keep this session open!${NC}"
    echo -e "${YELLOW}Test SSH in another terminal before closing this session.${NC}"
    read -p "Press Enter to continue..."
    sudo systemctl restart sshd
    echo -e "${GREEN}✓ SSH hardened - password auth disabled${NC}"
else
    echo -e "${RED}✗ SSH configuration invalid! Restoring backup...${NC}"
    sudo cp /etc/ssh/sshd_config.backup.$(date +%Y%m%d) /etc/ssh/sshd_config
    exit 1
fi

# Step 4: Configure UFW Firewall
echo -e "${YELLOW}[4/7] Configuring UFW firewall...${NC}"

# Reset UFW to clean state
sudo ufw --force reset

# Default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow SSH (CRITICAL - do this first!)
sudo ufw allow 22/tcp comment "SSH access"

# Allow HTTP/HTTPS for Caddy
sudo ufw allow 80/tcp comment "HTTP for Caddy"
sudo ufw allow 443/tcp comment "HTTPS for Caddy"
sudo ufw allow 443/udp comment "HTTP/3 QUIC"

# Allow SIP/RTP for Asterisk telephony
sudo ufw allow 5060/udp comment "SIP signaling"
sudo ufw allow 10000:10099/udp comment "RTP media"

# Enable firewall
sudo ufw --force enable
echo -e "${GREEN}✓ UFW firewall configured${NC}"
sudo ufw status numbered

# Step 5: Configure fail2ban
echo -e "${YELLOW}[5/7] Configuring fail2ban...${NC}"

sudo tee /etc/fail2ban/jail.local > /dev/null <<'F2BEOF'
# Kinder CRM - fail2ban Configuration
# Aggressive protection against attacks

[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
banaction = ufw

# SSH Protection
[sshd]
enabled = true
port = 22
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 7200

# Caddy/Web Server Protection (optional)
[caddy]
enabled = false
port = 80,443
filter = caddy
logpath = /var/log/caddy/access.log
maxretry = 20
findtime = 300
bantime = 3600
F2BEOF

sudo systemctl enable fail2ban
sudo systemctl restart fail2ban
echo -e "${GREEN}✓ fail2ban configured${NC}"
sudo fail2ban-client status

# Step 6: Install Docker
echo -e "${YELLOW}[6/7] Installing Docker...${NC}"

# Check if Docker is already installed
if command -v docker &> /dev/null; then
    echo -e "${YELLOW}Docker already installed, skipping...${NC}"
else
    # Add Docker's official GPG key
    sudo install -m 0755 -d /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    sudo chmod a+r /etc/apt/keyrings/docker.gpg

    # Add Docker repository
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    # Install Docker
    sudo apt update
    sudo apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin docker-buildx-plugin

    # Add user to docker group
    sudo usermod -aG docker $USER

    # Start Docker
    sudo systemctl enable docker
    sudo systemctl start docker
fi

echo -e "${GREEN}✓ Docker installed${NC}"
docker --version
docker compose version

# Step 7: Create directory structure
echo -e "${YELLOW}[7/7] Creating directory structure...${NC}"

sudo mkdir -p /opt/kinder
sudo mkdir -p /opt/kinder/secrets
sudo mkdir -p /backups/kinder
sudo mkdir -p /var/log/caddy

sudo chown -R $USER:$USER /opt/kinder
sudo chown -R $USER:$USER /backups/kinder
sudo chmod 700 /opt/kinder/secrets

echo -e "${GREEN}✓ Directories created${NC}"

# Summary
echo ""
echo "======================================"
echo -e "${GREEN}  SERVER SETUP COMPLETE!${NC}"
echo "======================================"
echo ""
echo "Configured:"
echo "  ✓ System packages updated"
echo "  ✓ SSH hardened (password auth disabled)"
echo "  ✓ UFW firewall enabled (22, 80, 443, 5060, 10000-10099)"
echo "  ✓ fail2ban configured"
echo "  ✓ Docker installed"
echo "  ✓ Directory structure created"
echo ""
echo -e "${YELLOW}IMPORTANT: Test SSH access in a new terminal before closing this session!${NC}"
echo -e "${YELLOW}Run: ssh yaro@213.109.146.167${NC}"
echo ""
echo "Next step: Run generate-secrets.sh to create strong passwords"
